// Next.js의 메타데이터 타입을 import (타이틀, 설명 등 정의에 사용)
import type { Metadata } from "next";

// Google Fonts에서 Inter 폰트를 가져오는 헬퍼 함수 import
import { Inter } from "next/font/google";

// 글로벌 스타일시트를 불러옵니다 (모든 페이지에 적용됨)
import "./globals.css";

// Clerk 인증(로그인/회원관리) 기능을 제공하는 Provider import
import { ClerkProvider } from "@clerk/nextjs";

import { Toaster } from "sonner";

// React Query를 전역적으로 사용할 수 있도록 해주는 Provider import
import { QueryProvider } from "@/providers/query-providers";
import SheetProvider from "@/providers/sheet-provider";

// Inter 폰트 설정 (latin 서브셋만 로드)
// 반환된 객체의 className을 body 태그에 적용해 폰트를 전역으로 설정
const inter = Inter({ subsets: ["latin"] });

// Next.js의 메타데이터 설정
// <head> 태그에 자동으로 삽입되어 SEO 및 브라우저 탭 정보로 활용됨
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Next.js App Router의 루트 레이아웃 컴포넌트
// 모든 페이지를 감싸며, 공통 Provider나 레이아웃을 설정할 수 있음
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode; // 모든 하위 페이지 컴포넌트가 여기에 렌더링됨
}>) {
  return (
    // ClerkProvider: 인증(로그인/로그아웃/세션 관리)을 전역적으로 활성화
    <ClerkProvider>
      <html lang="en">
        {/* body에 Inter 폰트를 적용하고, QueryProvider로 React Query 기능을 전역 제공 */}
        <body className={inter.className}>
          {/* QueryProvider: 서버 상태 관리(TanStack Query)를 앱 전역에 공급 */}
          <QueryProvider>
            <SheetProvider />
            <Toaster />
            {children}
          </QueryProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
